### ISSUE TITLE
Cursor<SmallVec<[u8; N]>> does not implement Write

### ISSUE THREAD

**Issue by rivertam** [servo/rust-smallvec#108]
I'd be pretty surprised if this weren't implemented for no good reason, but why is `SmallVec` not a `Read`? I'd like to be able to use it with the `byteorder` create like this:

```rust
    let mut cursor = std::io::Cursor::new(SmallVec::<[u8; 8]>::new());
    cursor.write_u16::<LittleEndian>(rand::random()).unwrap();
    cursor.write_u16::<LittleEndian>(rand::random()).unwrap();
    cursor.write_u16::<LittleEndian>(rand::random()).unwrap();
    cursor.write_u16::<LittleEndian>(rand::random()).unwrap();

    cursor.set_position(0);

    cursor.read_f64::<LittleEndian>().unwrap()
```

but this requires that `SmallVec` implement the `Read` trait.

**Comment by mbrubeck** [comment]
`Cursor<SmallVec<[u8; 8]>>` already implements the Read trait, thanks to this generic implementation in libstd:

```
impl<T> Read for Cursor<T> where T: AsRef<[u8]>
```

However, `Cursor<SmallVec>` does not implement the Write trait, since there's no similar generic implementation.  Fortunately you don't need a Cursor to write to a SmallVec.  You can do this:

```
    let mut v = SmallVec::<[u8; 8]>::new();
    v.write_u16::<LittleEndian>(rand::random()).unwrap();
    v.write_u16::<LittleEndian>(rand::random()).unwrap();
    v.write_u16::<LittleEndian>(rand::random()).unwrap();
    v.write_u16::<LittleEndian>(rand::random()).unwrap();

    let mut cursor = Cursor::new(v);
    cursor.read_f64::<LittleEndian>().unwrap()
```

or even this, since `&[u8]` implements `Read` without needing a `Cursor`:

```
    let mut v = SmallVec::<[u8; 8]>::new();
    v.write_u16::<LittleEndian>(rand::random()).unwrap();
    v.write_u16::<LittleEndian>(rand::random()).unwrap();
    v.write_u16::<LittleEndian>(rand::random()).unwrap();
    v.write_u16::<LittleEndian>(rand::random()).unwrap();

    v.as_slice().read_f64::<LittleEndian>().unwrap();
```

**Comment by rivertam** [comment]
@mbrubeck Thanks! The error messages I got here were a little confusing because they seemed to imply it was a read problem, not a write problem.
