### ISSUE TITLE
Add to_smallvec for the slice primitive type

### ISSUE THREAD

**Issue by sunjay** [servo/rust-smallvec#116]
The slice primitive type has a [`to_vec` method](https://doc.rust-lang.org/std/primitive.slice.html#method.to_vec) which makes it convenient to convert a slice to a vector. It would be great if this crate could define an extension trait that added a method called `to_smallvec` (or some other name) which did the same thing for `SmallVec`.

This makes it particularly convenient to port code to using SmallVec since you can just import that extension trait instead of converting all the calls to `to_vec`. :smiley:

**Comment by gootorov** [comment]
As an alternative, it could be done using `SmallVec::from_slice()` method.

**Comment by sunjay** [comment]
Yes, that's what I'm doing now, but going through and replacing lots of to_vec calls is tedious. It would be nice if it was possible to just find and replace the method call. :)
