### ISSUE TITLE
Possible UB from use of uninitialized `[&T; N]`

### ISSUE THREAD

**Issue by mbrubeck** [servo/rust-smallvec#126]
Creating an array with `mem::uninitialized` may be UB if the array's elements contain non-null types (like `&T`) or uninhabited types (like `!`) or other types that have invalid values.

This can result in undefined behavior even if you never read the elements directly while they are uninitialized.  For example, this program prints "true" if optimizations are enabled, when built with current rustc:

```rust
fn main() {
    let x: Option<[&u8; 1]> = unsafe { Some(std::mem::uninitialized()) };
    println!("{}", x.is_none());
}
```

`SmallVec` isn't eligible for null pointer optimization, so it isn't affected by this.  However, it's possible that a future Rust compiler could add other optimizations that break if SmallVec uses `mem::uninitialized` to create arrays of such types.

The ideal solution is to switch from `uninitialized` to the new `MaybeUninit` union (rust-lang/rfcs#1892) when it becomes stable.

**Comment by bluss** [comment]
`ManuallyDrop<T>` changed to allow enum layout optimization using the interior value, so it regressed this crate in that way. rust-lang/rust/pull/52711

**Comment by mbrubeck** [comment]
SmallVec contains an enum, so I think the enum layout optimization is using spare bits from that enum's tag to store the Option discriminant.  If this is true then we're not seeing incorrect behavior in practice *yet*.

**Comment by llogiq** [comment]
I recently looked into the use of `MaybeUninit<T>` in arrays. We'd need to extend the `Array` trait with an associated type of `type InternalArray = [MaybeUninit<$ty>; $n]` and use that internally. However that would require the `heap` variant to become (*mut MaybeUninit<A::Item>, usize) to ensure UB-freedom.
