### ISSUE TITLE
smallvec![] generate a "variable does not need to be mutable" warning.

### ISSUE THREAD

**Issue by crlf0710** [servo/rust-smallvec#127]
When use the macro to build an empty SmallVec, it raises a warning. I think this should be dealt with from the `smallvec` crate side.

**Comment by mbrubeck** [comment]
I can't reproduce this problem.  The following program compiles without warning for me, using Rust 1.29.1 and smallvec 0.6.5.

```
#[macro_use] extern crate smallvec;

use smallvec::SmallVec;

fn main() {
    let _foo: SmallVec<[u8; 1]> = smallvec![];
}
```

Can you create a test case that demonstrates the problem?

**Comment by crlf0710** [comment]
Mmm i tried to reduce the test case, and found that this code
```
#[macro_use] extern crate smallvec;

use smallvec::SmallVec;
use std::cell::RefCell;
pub struct R;

pub struct S {
    pub instances: RefCell<SmallVec<[R; 1]>>,
}

impl S {
    pub fn new() -> Self {
        S {
            instances: RefCell::new(smallvec![]),
        }
    }
}
```
issues such warning under stable 1.28.0:
```
warning: variable does not need to be mutable
  --> src\main.rs:14:37
   |
14 |             instances: RefCell::new(smallvec![]),
   |                                     ^^^^^^^^^^^ help: remove this `mut`
   |
   = note: #[warn(unused_mut)] on by default
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-
backtrace for more info)
```
But such warning is gone in the nightly channel (rustc 1.30.0-nightly (02cb8f2a4 2018-08-29)). I cannot reproduce using play.rust-lang.org's stable 1.29.* either.

I think maybe this is a fixed problem of rustc itself. Maybe we can close this now.

**Comment by mbrubeck** [comment]
Thanks for investigating!
