### ISSUE TITLE
Maybe remove the 'unreachable' crate dependency?

### ISSUE THREAD

**Issue by frewsxcv** [servo/rust-smallvec#128]
https://github.com/servo/rust-smallvec/blob/feb3e45d29e3c6690812164ffc95aa1369de656d/lib.rs#L48-L49

https://github.com/servo/rust-smallvec/blob/feb3e45d29e3c6690812164ffc95aa1369de656d/lib.rs#L762

Seems like we might be able to replace this usage with [this](https://doc.rust-lang.org/std/hint/fn.unreachable_unchecked.html):

```rust
use std::hint;

// ...

unsafe {
    self.pop().unwrap_or_else(hint::unreachable_unchecked)
}

**Comment by mbrubeck** [comment]
This would increase the minimum supported Rust version from 1.20 to 1.27.  Since this crate is so widely used, we try to batch such changes together along with other breaking changes.  Added this to the tracking bug (#73).
