### ISSUE TITLE
Why use `1usize` instead of `0usize` in unreachable?

### ISSUE THREAD

**Issue by playXE** [servo/rust-smallvec#158]
Why use `1usize` instead of `0usize` there :
```rust
#[inline]
pub unsafe fn unreachable() -> ! {
    enum Void {}
    let x: &Void = mem::transmute(1usize);
    match *x {}
}

```
If this function should trigger UB?

**Comment by emilio** [comment]
Doesn't really matter, to be clear, right?

It creates a null reference and dereferences it, so it's clearly UB regardless of the value of the reference.

Anyhow on trunk this has been replaced by `std::hint::unreachable_unchecked`.
