### ISSUE TITLE
Release a new version with stable alloc

### ISSUE THREAD

**Issue by roblabla** [servo/rust-smallvec#160]
Heyo, would it be possible to get a new release with the removed feature check around the alloc feature #159 ? Otherwise the alloc feature isn't usable on stable compilers. Thanks :).

**Comment by asajeffrey** [comment]
Cue conversation about whether this is a breaking change, requiring a major version bump, or not.

**Comment by mbrubeck** [comment]
#159 only affects builds without the 'std' feature, which was previously only possible with nightly Rust. Any existing stable Rust users are unaffected, so I would consider this a non breaking change. (Users of fairly old nightly Rust could be broken, but they were explicitly using unstable features and opted into this risk.)

**Comment by roblabla** [comment]
Alloc was stabilized in nightly nearly a month and a half ago. This will break nightly users older than that. Nightly users should be expecting breaking changes if they don't pin their dependencies anyways (and thankfully, this is the last time alloc breaks nightly users 🎉 ).

**Comment by dignifiedquire** [comment]
any update on this?

**Comment by roblabla** [comment]
Bump?

**Comment by mbrubeck** [comment]
Published version 0.6.11.
