### ISSUE TITLE
Request: new release (miri pass)

### ISSUE THREAD

**Issue by CAD97** [servo/rust-smallvec#177]
The latest published version (0.6.12) does not include [these commits](https://github.com/servo/rust-smallvec/compare/v0.6.12...master), which includes #162 which removes `mem::uninitialized` uses and lets the crate run under miri.

I was trying to run what appears to be a UB-based issue in a rust-analyzer (rowan) patch under miri and ran into this.

You should probably also consider submitting a RustSec advisory for the miri-disapproved `mem::uninitialized` usage.

<details><summary>Miri evaluation error</summary>

```
error[E0080]: Miri evaluation error: type validation failed: encountered uninitialized bytes at [0].inner.value, but expected a valid enum discriminant
   --> D:\usr\.cargo\registry\src\github.com-1ecc6299db9ec823\smallvec-0.6.12\lib.rs:409:49
    |
409 |                 data: SmallVecData::from_inline(mem::uninitialized()),
    |                                                 ^^^^^^^^^^^^^^^^^^^^ Miri evaluation error: type validation failed: encountered uninitialized bytes at [0].inner.value, but expected a valid enum discriminant
```
</details>

Side note: master still has a toml advertising a version number of `0.6.10`.

**Comment by mbrubeck** [comment]
I have an open PR #175 for a new release.
