### ISSUE TITLE
Implement Clone for IntoIter<A: Array> where A: Clone

### ISSUE THREAD

**Issue by robinhundt** [servo/rust-smallvec#178]
Implement Clone for IntoIter<A: Array> where A: Clone

This would be in line with the Iter struct that is returned when calling `into_iter()` on a `Vec`.
https://doc.rust-lang.org/std/slice/struct.Iter.html

**Comment by mbrubeck** [comment]
If someone would like to implement this, it could be done using `IntoIter::as_slice` (recently added in #182) and `SmallVec::from_slice`.
