### ISSUE TITLE
Add as_slice and as_mut_slice to smallvec::IntoIter

### ISSUE THREAD

**Issue by rklaehn** [servo/rust-smallvec#181]
SmallVec is mostly a drop in replacement for Vec. There are two methods on [std::vec::IntoIter](https://doc.rust-lang.org/std/vec/struct.IntoIter.html) that allow random access on the remainder of the iterator: [as_slice](https://doc.rust-lang.org/std/vec/struct.IntoIter.html#method.as_slice) and [as_mut_slice](https://doc.rust-lang.org/std/vec/struct.IntoIter.html#method.as_mut_slice). 

These are missing in SmallVec, but implementing them would be rather easy.

**Comment by rklaehn** [comment]
I gave it a shot...

**Comment by emilio** [comment]
Fixed by #182, thanks!
