### ISSUE TITLE
into_boxed_slice

### ISSUE THREAD

**Issue by zbraniecki** [servo/rust-smallvec#184]
Would it be hard to get an `into_boxed_slice` method for smallvec?

It would make replacing `Vec` for parsers which produce AST which stores `Box<[T]>` much easier.

**Comment by mbrubeck** [comment]
Sounds good. If you want to submit a pull request for this, it could be implemented as `self.into_vec().into_boxed_slice()`.

**Comment by L0uisc** [comment]
@mbrubeck your proposed solution will work, but won't it defeat the object of trying to replace `Vec` for parsers? I mean, then you simply end up allocating all vectors, even small ones, on the heap to be able to `Box` them. I understand that just making a slice pointing to some stack memory will be dangerous or extremely complex to keep safe, but what is the gain of using `SmallVec` then?

**Comment by mbrubeck** [comment]
`Box` is always a pointer to a heap allocation, so converting a non-spilled `SmallVec` into a `Box<[T]>` *must* allocate on the heap.  If you want to avoid the heap then you should not use `Box<[T]>`.

**Comment by L0uisc** [comment]
Can't you have a `Box<&T>` on the stack, pointing to a fat pointer on the heap (the actual `&T`), in turn pointing to a slice on the stack again? Anyway, I'm happy to take this up and implement your suggestion in the meantime ;)

**Comment by L0uisc** [comment]
Ah, yes, I thought about `Box<[&T]>`...
