### ISSUE TITLE
Smallvec good option for array language?

### ISSUE THREAD

**Issue by mamcx** [servo/rust-smallvec#194]
[Months ago](https://www.reddit.com/r/rust/comments/bi129v/microoptimization_for_interpreter_single_vect_or/) I asked about a better way to represent values that idiomatically are:

```rust
pub enum Array<T> {
    Zero([T; 0]),
    Scalar([T; 1]),
    Vec(Vec<T>),
}
pub enum Scalar {
  I32(Array<i32>),
  I64(Array<i64>),
}
```
This is for a array/relational language where scalar and multiples values are the same:
```
for i in [] do...
for i in 1 do... //same as [1]
for i in [1, 2, 3 ] do...
```
There was suggested this crate. Currently I put a Vec<T> for each scalar, but wonder if this crate allow to operate in an efficient way with 0 (I imagine alike vec, SmallVec not allocate for zero values?), 1 and N values. The main use case is to stream rows:

```rust
for row in [1,2,3;
                   4,5,6]
```
Where the values of rows are typically just [T; 1].

**Comment by mbrubeck** [comment]
Yes, `SmallVec<[T; 1]>` would be an efficient representation for this use case. It would only require allocation when the value contains multiple `T`.  Internally it is somewhat similar to your idiomatic `enum`.
