### ISSUE TITLE
Dedup functionality

### ISSUE THREAD

**Issue by iopq** [servo/rust-smallvec#2]
I'd like to `.sort()` and `.dedup()` the SmallVecs so I can see which values are unique. Failing that, I guess SmallHashSet would work too.

**Comment by iopq** [comment]
I don't actually know if it would be faster to do `.sort().` and `.dedup()` or to do a `.contains()` in a loop...

**Comment by SimonSapin** [comment]
`.sort()` should Just Work, through `DerefMut` to `[T]`. You may also want to try quicksort instead: https://github.com/servo/rust-quicksort it is not a *stable* sort (which doesn’t matter if you dedup) but it doesn’t allocate.

`Vec::dedup` can not be used directly, but I think its code can be copied mostly unchanged. It’d just need `.truncate(n)` to be added. I’d review a PR to do that.

As to which is faster, it depends on how many items you have and probably other things.

**Comment by SimonSapin** [comment]
It’s often hard to predict what algorithm is gonna be faster on a particular data set, the only way to *know* is to try and benchmark it.

**Comment by McGittyHub** [comment]
This is a feature that I would have liked to be able to use in my code.

**Comment by mbrubeck** [comment]
An implementation of `dedup` (and also `dedup_by` and `dedup_by_key`) would be very welcome. The `truncate` method was added in #12, so all these methods need to do is `swap` duplicate elements to the back of the vector and then `truncate` the vector to drop them.  (As mentioned above, you can use the code from `std::vec` for reference.)

**Comment by Thou94** [comment]
I would like to work on it, but it's my first time to contribute to an open source project. I would love to get some help, if I stuck somewhere.

**Comment by jdm** [comment]
@Thou94 A PR to implement those methods has already been submitted in #72.

**Comment by mbrubeck** [comment]
Fixed by #72, and will be included in version 0.6.0 (#78).
