### ISSUE TITLE
rustc-serialize and serde support

### ISSUE THREAD

**Issue by alexbool** [servo/rust-smallvec#23]
The name says it all :)

**Comment by Ms2ger** [comment]
I expect we'd take a PR implementing both behind their own feature gate.

**Comment by Xaeroxe** [comment]
PR for serde support: https://github.com/servo/rust-smallvec/pull/57

**Comment by mbrubeck** [comment]
Since rustc-serialize is deprecated and serde support has merged, I will mark this issue fixed.
