### ISSUE TITLE
Changing smallvec from 1.3.0 to 1.4.1 regresses Firefox's style system performance by ~10%

### ISSUE THREAD

**Issue by emilio** [servo/rust-smallvec#243]
I suspect the realloc changes might be to blame (40fa827 / 62a3622 / bdfc429, that is, #214), or a376b02 (#228), as they're the only functional changes afaict.

**Comment by emilio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1671170

**Comment by mbrubeck** [comment]
I'd be curious if #241 (on master but not yet released) fixes this regression. We could publish a new release with that patch included if that makes testing easier.

**Comment by mbrubeck** [comment]
> We could publish a new release with that patch included if that makes testing easier.

Filed #244 for this in case it's needed.

**Comment by emilio** [comment]
I bisected this locally and I think it's the "use realloc when possible" patch what causes the regression, but will bisect in automation on Monday. Will make sure to try 1.5.1 as well, thanks @mbrubeck!

**Comment by emilio** [comment]
Some preliminar investigation in https://bugzilla.mozilla.org/show_bug.cgi?id=1681003. It does seem related to bdfc4296d70112a17ef6077fb6653414b0979698.

I'm checking now whether this is something particular to our allocator, or a probabilistic checker we run to detect UAFs / etc, or whether it's something else.

But I suspect this is a Firefox allocator issue, off-hand.

**Comment by emilio** [comment]
Yeah, fix at https://phabricator.services.mozilla.com/D98924.
