### ISSUE TITLE
Compile union feature on 1.50 via ManuallyDrop?

### ISSUE THREAD

**Issue by saethlin** [servo/rust-smallvec#247]
On the 1.50 beta if I delete the `cfg_attr` for `feature = "union"`, I get this error message:
```rust
error[E0658]: unions with non-`Copy` fields other than `ManuallyDrop<T>` are unstable
   --> src/lib.rs:354:5
    |
354 |     inline: MaybeUninit<A>,
    |     ^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #55149 <https://github.com/rust-lang/rust/issues/55149> for more information
```
It doesn't take a lot to make the 1.50 (currently beta) compiler accept the code, but I'm a bit out of my depth here. Can we have the union feature on stable starting in 1.50?

**Comment by mbrubeck** [comment]
Yes, it looks like this works!  Please feel free to submit a pull request if you have a version that compiles already.  (Or I can do it, if you prefer.)  You can also change the documentation comment at the top of `src/lib.rs` to say that the `union` feature requires Rust 1.50.

**Comment by saethlin** [comment]
Closing, PR addressing this was merged
