### ISSUE TITLE
Missing FromIterator impl

### ISSUE THREAD

**Issue by Ten0** [servo/rust-smallvec#250]
The impl that enables to do `.collect()` is missing on smallvec:
https://doc.rust-lang.org/stable/std/iter/trait.FromIterator.html

**Comment by mbrubeck** [comment]
SmallVec does implement FromIterator:

https://docs.rs/smallvec/1.5.1/smallvec/struct.SmallVec.html#impl-FromIterator%3C%3CA%20as%20Array%3E%3A%3AItem%3E

https://docs.rs/smallvec/1.5.1/src/smallvec/lib.rs.html#1641-1648

**Comment by Ten0** [comment]
Whoops, right, my bad. Sorry.
