### ISSUE TITLE
support drain_filter ?

### ISSUE THREAD

**Issue by gcxfd** [servo/rust-smallvec#281]
https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.drain_filter

**Comment by L0uisc** [comment]
This seem like a good first issue. I also don't think it should be too difficult unless I'm missing something. @mbrubeck do you agree? Would you accept an implementation if someone contributes it? Or would you rather wait for the `std::Vec` counterpart to be stabilized?

**Comment by notgull** [comment]
I doubt that the API on the `std` equivalent will change between now and stabilization, so I'd support adding it!

**Comment by mbrubeck** [comment]
Yes, an implementation would be welcome!

**Comment by L0uisc** [comment]
I'm going to take a crack at it. Where do you have a Discord or something if I need to ask silly questions?

**Comment by mbrubeck** [comment]
I'm not personally active in any chat servers currently, but I'm happy to answer questions by email or in GitHub PR/issue comments.  I can also drop in to a Discord or Matrix room if you want to suggest one.

**Comment by L0uisc** [comment]
I've looked at it Saturday. The std implementation uses the unstable `Allocator` API, which can only be used inside std. I can probably implement it without the `A` generic parameter for now.

Secondly, my Rust is a little rusty. I've looked at the std implementation of `DrainFilter::next()`, and I see it's wrapped in an `unsafe` block. I couldn't quite understand it in the little time I looked at it Saturday either.

Finally, I'm still willing to do this, but I'm not going to get a lot of time for a deep dive between work and study. If someone else wants to do it or collaborate I'm more than willing to hand off or work together. I gathered that this isn't super urgent, so I'll get to it when I get to it if nobody else did it in the mean time. Is it fine like that, @mbrubeck?

**Comment by L0uisc** [comment]
I've done most of the implementation of `DrainFilter`. I want to add a couple more things:

- [ ] Feature flag for `drain_filter`.
- [ ] More and better tests.

I'd like some code review in the mean time already. I'm not 100% sure I understood everything the `std::vec::DrainFilter` and related `std::vec::Vec` code does, but I copied it pretty much verbatim. The tests are passing and it seems to be doing the right thing, but I would need a second pair of eyes to see if I missed something obvious that would cause unsoundness or something like that.

I also need guidance on how to add a feature flag for this project. Do you want to have `DrainFilter` behind a feature flag? If so, do you have any special conventions?

**Comment by L0uisc** [comment]
Writing tests, I found the `smallvec!` macro, but got a compile error when using it to create a non-empty `SmallVec`. I only saw a test for the empty case of the macro. Is the macro still working for non-empty initializer lists?

**Comment by mbrubeck** [comment]
> Writing tests, I found the smallvec! macro, but got a compile error when using it to create a non-empty SmallVec.

What error did you get?

**Comment by L0uisc** [comment]
Type inference error, could not deduce type for `A`. I figured it out. I was invoking it as follows:

```rust
assert_eq!(a, smallvec![1u8, 2, 4, 5, 7, 8]);
```

and the compiler couldn't deduce which Array type to use for stack storage. It works in the following case:

```rust
let a: SmallVec<[u8; 2]> = smallvec![1u8, 2, 3, 4, 5, 6, 7, 8];
```

**Comment by L0uisc** [comment]
I've made a PR. It has 10 commits, so I can clean up a bit if you want by squashing the commits into a few larger sensible groups. I can also still add more tests, but it's at least now covering the bare minimum of use cases.

**Comment by L0uisc** [comment]
@mbrubeck this issue can be closed now. Not sure why it didn't get closed automatically.
