### ISSUE TITLE
Make a pre-release for v2 branch on crates.io

### ISSUE THREAD

**Issue by DCNick3** [servo/rust-smallvec#320]
While, the v2 branch is not yet ready for full release yet, the current API is still much better than the array-based one, as it greatly simplifies generic code.

Can you please publish a pre-release on crates.io? I am fine with breaking changes later, it's just nicer to have a crates.io release than using a git-dependency

**Comment by mbrubeck** [comment]
Published version 2.0.0-alpha.1.  Thanks for testing smallvec v2!
