### ISSUE TITLE
Missing safety documentation for `Array` trait

### ISSUE THREAD

**Issue by djkoloski** [servo/rust-smallvec#350]
There are no comments describing the requirements for a type to implement the `Array` trait. This would be okay if `Array` was intended to be a sealed trait, but it can currently be implemented by anyone.

If this trait is not meant to be implemented downstream, can we seal it? Otherwise, can we have safety documentation for what types need to uphold to implement it?

**Comment by mbrubeck** [comment]
The `Array` trait should not be implemented downstream, and should be sealed.  (Before the `const_generics` feature existed, there was a potential use case for implementing it, but this is no longer true.)

The `Array` trait no longer exists in version 2.0.

**Comment by djkoloski** [comment]
Thanks for the details, I'm going to close this as completed for 2.0
