### ISSUE TITLE
Implement `std::error::Error` for `CollectionAllocErr`

### ISSUE THREAD

**Issue by JarvisCraft** [servo/rust-smallvec#355]
# Description

It seems unnatural that `CollectionAllocErr` currently does not implement `std::error::Error` which would come in handy in cases such as implementing `std::error::Error::source` on user-defined errors caused by `CollectionAllocErr`.

While `error_in_core` is not stable yet, such implementation could be hidden behind a feature flag such as (commmonly used) `std`.

Since the features should be additive (i.e. an inverted `no-std` feature would not be the  right approach), it is a breaking change to add such a feature so I suggest adding this to #183.

If this change is welcome, I may create a pull request to implement it.

cc @mbrubeck as the maintainer of the `2.0` wishlist

**Comment by mbrubeck** [comment]
Yes, a pull request to the `v2` branch would be welcome.

I don't think this is a breaking change.  Adding a disabled-by-default `std` feature should have no effect on existing users of the crate.  However, I prefer not to make any unnecessary changes to v1 at this point.  Also, if we do this on v2 then we can also deprecate the `write` feature in favor of the new `std` feature.
