### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Marwes** [servo/rust-smallvec#36]
Any chance of a new release sometime soon? Would like to have access to the [Default impl](4e754ee85315f139f589201d5e904b938c8af201).

**Comment by emilio** [comment]
I published this a few minutes ago, thanks for noticing!

Next time, feel free to add your PR with a version bump, so it's published right away :)

Thanks again!

**Comment by Marwes** [comment]
Wasn't in a hurry to have the `Default` impl when I made the PR and I didn't want to mess with versioning. Only relalized I needed it after resurrecting an old PR today. Thanks!
