### ISSUE TITLE
Collecting from iterator skips Nth item

### ISSUE THREAD

**Issue by Gingeh** [servo/rust-smallvec#365]
Code to reproduce:
```rs
use smallvec::SmallVec;

fn main() {
    let input = "0123456";
    let collected: SmallVec<char, 4> = input
        .chars()
        .collect();

    println!("{collected:?}");
    // expected: ['0', '1', '2', '3', '4', '5', '6']
    // actual:   ['0', '1', '2', '3', '5', '6']
}
```

This only occurs in 2.0 alpha versions, it also did not occur when collecting from a range.

**Comment by mbrubeck** [comment]
Thanks for the report! This is fixed in 2.0.0-alpha.9.

**Comment by Gingeh** [comment]
Thank you! That was very quick

**Comment by mbrubeck** [comment]
Just for reference, this bug was introduced in #362.  The only affected version was smallvec 2.0.0-alpha.8.
