### ISSUE TITLE
Dropping SmallVecN is unsound

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-smallvec#4]
For example, this segfaults:
```rust
SmallVec4::<Box<u32>>::new();
```

`SmallVec4<T>` contains a `[T; 4]` field directly, which is initialized in `new` with `std::mem::zeroed()`. When the vector is dropped, the destructor for `T` is run for each of the 4 `T`s, even if there isn’t actually a `T` there (i.e. if the vector’s length is less than 4 by the time it is dropped).

https://github.com/bluss/arrayvec works around this issue by having (simplified):
```rust
enum Array<T> {
    Alive([T, 4]),
    Dropped,
}
```
with a destructor that resets to `Dropped` before the recursive destructors are run implicitly.

In `SmallVecN`, the second variant could instead contain the pointer and capacity for a spilled vector (reset to null/zero during destruction).

**Comment by SimonSapin** [comment]
CC @pcwalton

**Comment by SimonSapin** [comment]
I think this used to be sound when Rust had both drop flags and zeroing-on-drop, but that changed in https://github.com/rust-lang/rust/pull/23535.

We *could* probably go back to the old behavior by initializing with `std::mem::POST_DROP_U8` instead of zeroes, but I think that’s not a good idea since drop flags are probably going away entirely.

https://github.com/rust-lang/rfcs/pull/197 is also relevant.

**Comment by bluss** [comment]
The replacement for zeroed is `mem::dropped` with filling drop.

**Comment by SimonSapin** [comment]
Using `dropped` instead of `zeroed` could be a short-term fix, but it requires `#![feature(filling_drop)]` whereas the library currently runs (also brokenly) on Rust stable. I’d prefer using `NoDrop` from arrayvec.
