### ISSUE TITLE
Bump version number to include extend_from_slice

### ISSUE THREAD

**Issue by nipunn1313** [servo/rust-smallvec#41]
Hi friends,

Would be great if we could bump a new release to include the new functions (insert_from_slice and extend_from_slice) that landed a couple months back.

Thanks!

**Comment by mbrubeck** [comment]
I'll bump the version number and publish a new version as soon as #44 is resolved.

**Comment by mbrubeck** [comment]
https://crates.io/crates/smallvec/0.3.2
