### ISSUE TITLE
impl std::io::Write for SmallVec<[u8, N]>

### ISSUE THREAD

**Issue by chpio** [servo/rust-smallvec#51]
Simple impl calling the `extend_from_slice` fn should do the trick.

Are there any cons to this?

**Comment by kotakotik22** [comment]
is there any reason this issue was closed? `Write` is still not implemented for `SmallVec<[u8; N]>` in `1.31.1` or `SmallVec<u8, N>` in `2.0.0-alpha.4`

**Comment by mbrubeck** [comment]
`Write` is implemented for `SmallVec<[u8; N]>` as long as the default `std` feauture is not disabled.

**Comment by mbrubeck** [comment]
`Write` is implemented for `SmallVec<[u8; N]>` when the [`write` Cargo feature](https://docs.rs/smallvec/latest/smallvec/#write) is enabled.

* https://docs.rs/smallvec/1/smallvec/struct.SmallVec.html#impl-Write-for-SmallVec%3CA%3E
* https://docs.rs/smallvec/2.0.0-alpha.4/smallvec/struct.SmallVec.html#impl-Write-for-SmallVec%3Cu8,+N%3E
