### ISSUE TITLE
MIT/Apache relicensing

### ISSUE THREAD

**Issue by raviqqe** [servo/rust-smallvec#83]
I'll appreciate that if this crate is relicensed under MIT/Apache as Rust.

**Comment by mbrubeck** [comment]
I agree.

For those of us who contributed to this crate in our role as Mozilla employees, we'd need Mozilla to sign off on this, which I expect it would be willing to do.  @larsbergstrom, is there an established process for requesting this?

We will also need sign-off from all non-employee individual copyright holders.  We can contact them if we decide to make this change.

For reference, here is the contribution history of this code before it was moved to this repo:

https://github.com/servo/rust-selectors/blame/e8dd4cfe4d6a40363ca5df468b29121fe25a7956/src/smallvec.rs

https://github.com/servo/servo/blame/d26345f868e4261760ce204bdc383941e8f14621/components/util/smallvec.rs

**Comment by larsbergstrom** [comment]
@mbrubeck I'll check with legal, but in general for non-strategic code bases it is acceptable to use the predominant license of the community. I'll post back here with yes/no. Thanks for checking with me!

**Comment by larsbergstrom** [comment]
@mbrubeck Yes, we can do this in the same way as the following:
https://github.com/servo/gleam/issues/57

That is, we list all of the contributors, have each of them sign off on the transfer, and then we can move forward.

**Comment by raviqqe** [comment]
Any progress or decisions so far? Can I help by doing something?

**Comment by cramertj** [comment]
Ping @mbrubeck @larsbergstrom would it be possible to start this license change check-off? (as in https://github.com/servo/gleam/issues/57)

**Comment by mbrubeck** [comment]
Hello!  The Servo team would like to make the `smallvec` Rust crate available under the dual MIT/Apache-2.0 license used by Rust itself and by most open source Rust crates.  The `smallvec` crate is currently published under the Mozilla Public License 2.0, because it was originally part of the `servo` repo which is under that license.

To change the license, we need permission from all of the copyright holders.  If you have contributed code or documentation to this crate, your username should be listed below.  If you agree to re-license your contributions, please comment on this issue with the following statement:

> I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

Below is a list of all the accounts who contributed copyrightable changes to this crate.  This includes open PRs, and excludes commits that only contained trivial mechanical changes like version bumps or git merges.

- [ ] @AerialX
- [ ] @Amanieu
- [ ] @arthurprs
- [ ] @bluss
- [ ] @c0gent
- [ ] @cfallin
- [ ] @cgaebel
- [ ] @chpio
- [ ] @cramertj
- [ ] @dbkaplun
- [ ] @hoggetaylor
- [ ] @Marwes
- [ ] @mbrubeck
- [ ] @Ms2ger
- [ ] @nipunn1313
- [ ] @pcwalton
- [ ] @Pratyush
- [ ] @SergioBenitez
- [ ] @SimonSapin
- [ ] @tomaka
- [ ] @Vurich
- [ ] @Xaeroxe

**Comment by mbrubeck** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Xaeroxe** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by chpio** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by pcwalton** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by arthurprs** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Amanieu** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by cramertj** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by c0gent** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Marwes** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by SimonSapin** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Pratyush** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by dbkaplun** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by hoggetaylor** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by AerialX** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by nipunn1313** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by bluss** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Ms2ger** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by tomaka** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by SergioBenitez** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by mbrubeck** [comment]
@cgaebel's contributions were made as a Mozilla employee, so I believe Mozilla's approval is sufficient in that case.  If so, that's everyone.  Thank you all!
