### ISSUE TITLE
Is there a way to convert a SmallVec<A> into an A?

### ISSUE THREAD

**Issue by sunshowers** [servo/rust-smallvec#85]
I have need for a variable-length array that is almost always exactly length 32 -- so I'd like to represent it as a `SmallVec<[T; 32]>`. I'd like to convert it to a `[T; 32]` without copying. It would be cool to add a method that can try doing the conversion if possible and returns the original `SmallVec` if it didn't work out:

```
fn into_array(self) -> Result<A, Self>
```

What do you think?

**Comment by mbrubeck** [comment]
Fixed by #115.
