### ISSUE TITLE
smallvec! macro requires T to be Copy

### ISSUE THREAD

**Issue by samnardoni** [servo/rust-smallvec#98]
The `smallvec!` macro, when using the `smallvec![a,b,c]` form, requires that `T: Copy`. 

This is because the macro expands to use `SmallVec::from_slice`. 

```
    ($($x:expr),*) => ({
        SmallVec::from_slice(&[$($x),*])
    });
```

Perhaps it could instead expand into something like...

```
let s = SmallVec::new();
s.push(a);
s.push(b);
s.push(c);
s
```
... and remove the need for `T: Copy`?

**Comment by RReverser** [comment]
@samnardoni @jdm I made a PR to fix this issue in a relatively performant manner.
